# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '003RAC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 003RAC
  pod 'ReactiveObjC', '~> 3.1.1'
end
