# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target '01Animation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for 01Animation
  pod 'SWRevealViewController', '~> 2.3.0'
  pod 'DCPathButton', '~> 2.1.4'
  pod 'DWBubbleMenuButton', '~> 1.0.1'
  pod 'MCFireworksButton', '~> 0.1'

end
