# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target '003OpenCV' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 003OpenCV
  pod 'OpenCV', '~> 3.4.2'

end
